create table usr_phone (id binary generated by default as identity,
 ph_city_code int not null, 
 ph_contry_code varchar(3) not null,
 ph_number BIGINT not null, user_id binary,
 primary key (id));

 
create table usr_user (usr_id binary not null,
 usr_created timestamp not null,
 usr_name varchar(30) not null,
 usr_email varchar(30),
 usr_isactive boolean not null,
 usr_last_login timestamp not null,
 usr_modified timestamp,
 usr_password varchar(255) not null,
 usr_token varchar(255) not null,
 primary key (id));

alter table usr_user drop constraint if exists UK_usr_email;
alter table usr_user add constraint UK_usr_email unique (usr_email);
alter table usr_phone add constraint FK_ph_user_id foreign key (ph_user_id) references usr_user;


